### ISSUE TITLE
HTTP VS HTTPS MIXED CONTENT

### ISSUE THREAD

**Issue by nilill** [anddero/ajukraanid#3]
Mixed Content: The page at 'https://nilill.github.io/newGameConfirmation' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://18.220.101.130:8080/'. This request has been blocked; the content must be served over HTTPS.
(anonymous) @ vue-resource.esm.js:1072
a @ vue-resource.esm.js:196
M @ vue-resource.esm.js:1019
I @ vue-resource.esm.js:1168
r @ vue-resource.esm.js:1133
q @ vue-resource.esm.js:1375
q.(anonymous function) @ vue-resource.esm.js:1414
created @ NewGameConfirmation.vue:47
we @ vue.esm.js:2895
un._init @ vue.esm.js:4560
a @ vue.esm.js:4728
(anonymous) @ vue.esm.js:4242
init @ vue.esm.js:4059
(anonymous) @ vue.esm.js:5512
l @ vue.esm.js:5460
(anonymous) @ vue.esm.js:5749
C @ vue.esm.js:5840
(anonymous) @ vue.esm.js:6000
t._update @ vue.esm.js:2647
(anonymous) @ vue.esm.js:2765
je.get @ vue.esm.js:3115
je.run @ vue.esm.js:3192
Ee @ vue.esm.js:2954
(anonymous) @ vue.esm.js:1813
Kt @ vue.esm.js:1734

**Comment by anddero** [comment]
Not an AWS issue. SSL/TLS is an application layer protocol and must be enabled in Spring Boot to connect via HTTPS.

**Comment by anddero** [comment]
Fixed.
