### ISSUE TITLE
Cannot kick players from lobby

### ISSUE THREAD

**Issue by anddero** [anddero/ajukraanid#7]
If you kick a person, the application seems to try to always kick the first player in the list. And after a few seconds the person reappears.

See video: https://www.dropbox.com/s/fvmfti0bs6zqbkk/Brainvalves%20-%20Google%20Chrome%204_1_2018%206_41_16%20PM.mp4?dl=0

**Comment by nilill** [comment]
ETA 24h

**Comment by nilill** [comment]
The name that fontend tryed to send was undefined.
